# Generated by Django 5.2.4 on 2025-07-04 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_needed', models.CharField(choices=[('alaga', 'Alaga Ìdúró & Ìjòkò'), ('letters', 'Proposal & Acceptance Letters'), ('consult', 'Consultation for Couples'), ('eru', 'Ẹrú Ìyàwó Support')], max_length=20)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('marital_status', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('occupation', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=50)),
                ('proposed_date', models.DateField()),
                ('bride_name', models.CharField(max_length=150)),
                ('bride_oriki', models.CharField(blank=True, max_length=255)),
                ('bride_occupation', models.CharField(blank=True, max_length=100)),
                ('bride_favorite_artist', models.TextField(blank=True)),
                ('bride_religion', models.CharField(blank=True, max_length=50)),
                ('bride_email', models.EmailField(blank=True, max_length=254)),
                ('bride_father_name', models.CharField(blank=True, max_length=150)),
                ('bride_father_state', models.CharField(blank=True, max_length=100)),
                ('bride_father_hometown', models.CharField(blank=True, max_length=100)),
                ('bride_father_family_compound', models.CharField(blank=True, max_length=100)),
                ('bride_father_occupation', models.CharField(blank=True, max_length=100)),
                ('bride_father_religion', models.CharField(blank=True, max_length=50)),
                ('bride_father_best_songs', models.TextField(blank=True)),
                ('bride_mother_name', models.CharField(blank=True, max_length=150)),
                ('bride_mother_maiden_name', models.CharField(blank=True, max_length=150)),
                ('bride_mother_hometown', models.CharField(blank=True, max_length=100)),
                ('bride_mother_family_compound', models.CharField(blank=True, max_length=100)),
                ('bride_mother_occupation', models.CharField(blank=True, max_length=100)),
                ('bride_mother_religion', models.CharField(blank=True, max_length=50)),
                ('groom_name', models.CharField(max_length=150)),
                ('groom_oriki', models.CharField(blank=True, max_length=255)),
                ('groom_religion', models.CharField(blank=True, max_length=50)),
                ('groom_occupation', models.CharField(blank=True, max_length=100)),
                ('groom_favorite_artist', models.TextField(blank=True)),
                ('groom_father_name', models.CharField(blank=True, max_length=150)),
                ('groom_father_state', models.CharField(blank=True, max_length=100)),
                ('groom_father_hometown', models.CharField(blank=True, max_length=100)),
                ('groom_father_family_compound', models.CharField(blank=True, max_length=100)),
                ('groom_father_occupation', models.CharField(blank=True, max_length=100)),
                ('groom_father_favorite_artist', models.TextField(blank=True)),
                ('groom_mother_name', models.CharField(blank=True, max_length=150)),
                ('groom_mother_maiden_name', models.CharField(blank=True, max_length=150)),
                ('groom_mother_state', models.CharField(blank=True, max_length=100)),
                ('groom_mother_hometown', models.CharField(blank=True, max_length=100)),
                ('groom_mother_family_compound', models.CharField(blank=True, max_length=100)),
                ('groom_mother_religion', models.CharField(blank=True, max_length=50)),
                ('groom_mother_occupation', models.CharField(blank=True, max_length=100)),
                ('groom_mother_favorite_artist', models.TextField(blank=True)),
                ('share_on_social_media', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecentWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('tiktok', 'TikTok')], max_length=50)),
                ('video_url', models.URLField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecentWorkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='recent_works/')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.recentwork')),
            ],
        ),
    ]
